AllCops:
  Include:
    - 'lib/*/*.rb'
    - 'lib/*.rb'
    - '**/*.rb'
  Exclude:
    - 'README.md'
Style/FrozenStringLiteralComment:
  Enabled: true

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 30

Layout/LineLength:
  Max: 120

Metrics/AbcSize:
  Max: 25

Style/HashEachMethods:
  Enabled: false

Style/HashTransformKeys:
  Enabled: false

Style/HashTransformValues:
  Enabled: false
